name: Terraform Destroy (manual)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: gha-terraform-destroy
      - uses: hashicorp/setup-terraform@v3
      - name: Destroy
        run: terraform -chdir=infra destroy -auto-approve
